### ISSUE TITLE
Disappearing icons in Chrome

### ISSUE THREAD

**Issue by madoublet** [PolymerElements/iron-icon#20] opened 2015-05-31 02:42 UTC
I have noticed an odd bug in Chrome.  The icons work as expected in both Firefox and Safari.  But, in Chrome, sometimes the icons are displayed and other times they do not.  I do not have any errors showing in the console in both cases.  If I refresh the site enough, they will show eventually.  

The odd thing is that when they do not display, the rendered HTML is as follows:

```
  <iron-icon icon="language" class="style-scope respond-languages-toggle x-scope iron-icon-0">
    <iron-meta id="meta" type="iconset" class="style-scope iron-icon"></iron-meta>
  </iron-icon>
```

When they do display, the rendered HTML is as follows:

```
<iron-icon icon="search" class="style-scope respond-search-toggle x-scope iron-icon-0"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" class="style-scope iron-icon" style="pointer-events: none; display: block; width: 100%; height: 100%;"><g class="style-scope iron-icon"><path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z" class="style-scope iron-icon"></path></g></svg>
    <iron-meta id="meta" type="iconset" class="style-scope iron-icon"></iron-meta>
  </iron-icon>
```

The iron-icon is loaded in another component.  You can view the source here:
https://github.com/madoublet/respond/blob/dev/site/components/respond-search-toggle.html

You can see a demo of this behavior here: http://dev.respondcms.com/sites/one/index

There should be a search icon in the circle in the top right.

**Comment by madoublet** [comment] 2015-05-31 14:22
I did some more testing.  It appears that the icon does not load on a clear cache.  It will load every subsequent page load.  Also, it does not load if you refresh the page.

**Comment by madoublet** [comment] 2015-05-31 14:23
Also, I verified the same thing is happing if I try to load an icon outside of another web component.

**Comment by mattiLeBlanc** [comment] 2015-06-02 03:07
I have the same issue, my icons are not rendered in Chrome:

```
<link rel="import" href="/components/iron-icon/iron-icon.html">
<link rel="import" href="/components/iron-icons/iron-icons.html">
<link rel="import" href="/components/iron-icons/social-icons.html">
```

then just running this jade markup:

```
paper-menu
                     paper-icon-item
                        iron-icon(icon="inbox" item-icon)
                        | Inbox
```

results in the message: [iron-icon::_updateIcon]: could not find iconset `icons`, did you import the iconset?
Works fine in Safari

Running the demo locally works fine: http://localhost:3000/components/paper-item/demo/index.html
So ...It might be related to Meteor?
I don't see anything weird in the load order though

**Comment by madoublet** [comment] 2015-06-02 03:19
I imported the icons using the following:

```
<link rel="import" href="lib/iron-icons/iron-icons.html">
-<link rel="import" href="lib/iron-icons/maps-icons.html">
```

I gave up on this. A quick fix is to just use the raw SVG code, so I opted for that.

**Comment by sjmiles** [comment] 2015-06-03 06:38
duplicate of #19

**Closed as completed** 2015-06-10 00:10 UTC
