### ISSUE TITLE
iron-icons not rendering on Firefox

### ISSUE THREAD

**Issue by jeffrey-l-turner** [PolymerElements/iron-icon#58] opened 2016-01-12 01:08 UTC
Several of the icons are not rendering on Firefox. This can be verified by using Firefox on the demo page at: https://elements.polymer-project.org/elements/iron-icons?view=demo:demo/index.html&active=iron-icons

Non-rendering icons include: b, d, indeterminate-check-box, & gif.

I have verified that the generated svg code renders by itself properly. So it appears to have to something with the svg or g wrapping elements.

**Comment by jeffrey-l-turner** [comment] 2016-01-12 18:24
I researched this a bit more, it appears that the <svg> and <g> wrappers without the  <iron-icon class="x-scope iron-icon-0"> element render properly. The icon fails to render with the <iron-icon> polymer element wrapper is used. Haven't had a chance to debug further...

**Comment by notwaldorf** [comment] 2016-01-12 19:34
Duplicate of https://github.com/PolymerElements/iron-icons/issues/28. We've updated some of these in a recent release, and should make it to the catalog soon.

**Closed as completed by notwaldorf** 2016-01-12 19:34 UTC
