### ISSUE TITLE
Deprecation notice from flex layout

### ISSUE THREAD

**Issue by jensenbox** [PolymerElements/iron-icon#65] opened 2016-03-31 17:38 UTC
### Description

As per the notation at https://github.com/PolymerElements/iron-flex-layout/blob/master/classes/iron-flex-layout.html#L14 modules should no longer be referencing the iron-flex-layout/iron-flex-layout.htm document.
### Expected outcome

No console warning
### Actual outcome

<script>
  console.warn('This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead');
</script>

**Comment by notwaldorf** [comment] 2016-03-31 19:23
Neither `iron-icon` [itself](https://github.com/PolymerElements/iron-icon/blob/master/iron-icon.html#L13) nor its [demo](https://github.com/PolymerElements/iron-icon/blob/master/demo/index.html#L17)  are using the deprecated classes version and I cannot reproduce this in a [jsbin](http://output.jsbin.com/biziqi).

Where are you seeing this warning? Are you using the latest version of the elements?

Closing this, since it's not reproducible, but please let us know when you have repro steps that we can look at!

**Closed as completed by notwaldorf** 2016-03-31 19:23 UTC

**Comment by jensenbox** [comment] 2016-03-31 19:32
Thanks for the response.

I will see what I can do about putting a demo together.

in the mean time, if you do a bower update your iron-flex-layout will bump to 1.3.1 - in that instance every time the non-classes reference will emit a log indicating the deprecation.

This is what causes it: "iron-flex-layout": "PolymerElements/iron-flex-layout#1.3.1",
