### ISSUE TITLE
changing color doesn't work as documented

### ISSUE THREAD

**Issue by nylki** [PolymerElements/iron-icon#55] opened 2015-11-10 10:12 UTC
The [documentation](https://github.com/PolymerElements/iron-icon#styling) says: 

``` .css
    --iron-icon-fill-color: green
```

However this doesn't seem to work on my side ( "polymer": "~1.2.1", "iron-elements": "~1.0.4").
Also the width/height change attributes don't seem to take effect.

html:

``` .html
<iron-selector id="tool-box" attr-for-selected="name" selected="polygon">
    <iron-icon class="tool-box-icon" name="polygon" src="images/IconTool_BLACK/IconTools_Path_black.svg"></iron-icon>
    <iron-icon class="tool-box-icon" name="compare" src="images/IconTool_BLACK/IconTools_Compare_black.svg"></iron-icon>
    <iron-icon class="tool-box-icon" name="freehand" src="images/IconTool_BLACK/IconTools_Brush_black.svg"></iron-icon>
    <iron-icon class="tool-box-icon" name="text" src="images/IconTool_BLACK/IconTools_Text_black.svg"></iron-icon>
</iron-selector>

```

css:

``` .css
.tool-box-icon .iron-selected {

  --iron-icon-fill-color: white;
}

.tool-box-icon *:not(.iron-selected):hover {

    --iron-icon-fill-color: blue;

}
```

**Comment by notwaldorf** [comment] 2015-11-10 21:57
It would be great if you could reproduce this in a jsbin, however just by looking at your code, I think you aren't using the correct css selector for custom properties. It should use the custom element you are targetting, so something like:

``` css
iron-icon.tool-box-icon .iron-selected {
  --iron-icon-fill-color: white;
}

iron-icon.tool-box-icon *:not(.iron-selected):hover {
   --iron-icon-fill-color: blue;
}
```

Also make sure all of these are in a `<style is="custom-style">` tag.

**Comment by nylki** [comment] 2015-11-11 12:35
@notwaldorf here is a minial jsbin for you:
http://jsbin.com/riqeqepohe/edit?html,output

I had some progress. It seems that only icons defined in icon-sets can be styled with `--iron-icon-fill-color` and `--iron-icon-stroke-color`, but no `iron-icon`'s that are loaded directly from an svg via `src=""`

If this behavious is supposed to be like this, I suggest mentioning it in the documentation. Otherwise a fix would be very welcome :)

**Comment by nylki** [comment] 2015-11-20 09:36
@notwaldorf any news?

**Comment by cdata** [comment] 2016-02-03 23:11
It looks like the styles are being applied, but the icon itself is not picking them up. In the first part of your example, where you use an `.svg` image src, you wouldn't get the special styles anyway (styling SVG like that is not allowed).

**Comment by cdata** [comment] 2016-02-03 23:13
I think that this icon might just be malformed. I'm going to close this issue because there probably isn't anything we can do about it.

**Closed as completed by cdata** 2016-02-03 23:13 UTC
Labels: pending-response

**Comment by snorberhuis** [comment] 2016-04-18 09:59
For reference, I had a similar problem where --iron-icon-fill-color did not work. This was because the fill color was hardcoded in the icon.
